fix. vite.docs.yml update.

diff --git a/.github/workflows/vite.docs.yml b/.github/workflows/vite.docs.yml
--- a/.github/workflows/vite.docs.yml
+++ b/.github/workflows/vite.docs.yml
@@ -1,7 +1,8 @@
-name: Deploy vite built sites to github pages
+name: Deploy static content to Pages
 on:
   push:
     branches: ['main']
+
   workflow_dispatch:
 
 permissions:
@@ -20,18 +21,19 @@ jobs:
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Setup Node.js 22
-        uses: actions/setup-node@v4
-        with:
-          node-version: '22'
-          
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: clone solidbase theme github
         run: |
-          git clone https://github.com/nikescar/ghaction-ghpage-solidbase-builder.git .solidbase --depth 1
+          export theme_upstream=$(grep -m1 'theme_upstream:' _config.yml | awk '{print $2}' | sed "s/'//g")/archive/refs/heads/main.tar.gz
+          wget -q "$theme_upstream" -O main.tar.gz
+          if [ $? -ne 0 ]; then
+              echo "Failed to download theme from $theme_upstream"
+              exit 1
+          fi
+          mkdir -p .solidbase
+          tar -xzf main.tar.gz --strip-components=1 -C .solidbase
           pushd ./.solidbase
           bash ghworkflow.sh
           popd
